# apiVersion: kustomize.config.k8s.io/v1beta1
# kind: Kustomization
resources:
- daemonset.yaml
- rbac.yaml
configMapGenerator:
- name: promtail-config
  files:
  - config.yaml
commonLabels:
  app: promtail
  role: logging
images:
- name: grafana/promtail
  newName: harbor.wzs.wistron.com.cn/grafana/promtail
  newTag: v0.3.0
